AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: disable

# ------------------------------------------------------- Layout -------------------------------------------------------

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/LineLength:
  Max: 120

# ------------------------------------------------------- Style --------------------------------------------------------

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# ------------------------------------------------------- Metrics ------------------------------------------------------

Metrics/BlockLength:
  Enabled: false
